apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deploy
  labels:
     app: myjava
spec:
  replicas: 3
  selector:
    matchLabels:
       app: myjava
  template:
    metadata:
       labels:
        app: myjava
    spec:
      containers:
      - name: myjavaapp-container
        image: maha4iac/myonlinestore28july:1
        ports:
        - containerPort: 8080