apiVersion: v1
kind: ReplicationController
metadata: 
  name: myjava-rc
spec:
  replicas: 3
  selector: 
    app: myjava-pod
    version: 2.7.1
  template:
   metadata:
    labels:
     app: myjava-pod
     version: 2.7.1
   spec:
    containers:
    - name: myjava-container
      image: maha4iac/mahaonlinestore:1
      ports:
      - containerPort: 8080
     